// <auto-generated />
namespace Hope.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2903_2_____ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2903_2_____));
        
        string IMigrationMetadata.Id
        {
            get { return "201803291415343_2903_2_____"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
